In [156]:
import pandas as pd
import numpy as np

In [157]:
import os
os.getcwd()

'c:\\Users\\SREESHANTH_K\\Desktop\\etl'

In [ ]:
df = pd.read_csv("datasets\Canberra_observations.csv", sep="\t")

In [159]:
df.head()

,Date,Time,Wind dir,Wind spd,Wind gust,Tmp,Dew pt,Feels like,rh,Fire,Rain,Rain 10',Pres
0,01/01/2013,Wed 00:00 EDT,WNW,9,9,19.6,0.1,19.6,27,12,0.0,0.0,1011.4
1,01/01/2013,Tue 23:30 EDT,WNW,-,13,20.7,0.7,20.7,26,13,0.0,0.0,1011.1
2,01/01/2013,Tue 23:00 EDT,W,9,11,22.8,0.9,22.8,23,15,0.0,0.0,1011.0
3,01/01/2013,Tue 22:30 EDT,WNW,11,13,22.6,-1.0,22.6,21,17,0.0,0.0,1011.0
4,01/01/2013,Tue 22:00 EDT,WNW,15,19,23.9,-2.2,23.9,18,21,0.0,0.0,1011.1

In [160]:
df.shape

(19918, 13)

In [161]:
df.dtypes

Date          str
Time          str
Wind dir      str
Wind spd      str
Wind gust     str
Tmp           str
Dew pt        str
Feels like    str
rh            str
Fire          str
Rain          str
Rain 10'      str
Pres          str
dtype: object

In [162]:
df.duplicated().sum()

np.int64(0)

In [163]:
df.isnull().sum()

Date          0
Time          0
Wind dir      0
Wind spd      0
Wind gust     0
Tmp           0
Dew pt        0
Feels like    0
rh            0
Fire          0
Rain          0
Rain 10'      0
Pres          0
dtype: int64

In [164]:
df["Date"].value_counts(dropna=False)

Date
12/06/2013    82
20/07/2013    77
18/05/2013    75
26/05/2013    75
07/04/2013    73
              ..
07/11/2013    46
15/08/2013    43
27/03/2013    40
25/03/2013    38
26/03/2013    33
Name: count, Length: 365, dtype: int64

In [165]:
df["Wind dir"].value_counts(dropna=False)

Wind dir
-      1963
N      1940
NNW    1937
NW     1891
E      1672
WNW    1639
S      1319
ESE    1307
SE     1237
SSE    1136
W      1009
ENE     791
NNE     636
NE      564
SSW     356
WSW     285
SW      236
Name: count, dtype: int64

In [166]:
df.dtypes

Date          str
Time          str
Wind dir      str
Wind spd      str
Wind gust     str
Tmp           str
Dew pt        str
Feels like    str
rh            str
Fire          str
Rain          str
Rain 10'      str
Pres          str
dtype: object

In [167]:
df[["Tmp", "Feels like"]]

        Tmp Feels like
0      19.6       19.6
1      20.7       20.7
2      22.8       22.8
3      22.6       22.6
4      23.9       23.9
...     ...        ...
19913  11.6       11.0
19914  12.0       11.5
19915  13.1       12.7
19916  12.7       12.3
19917  13.4       13.1

[19918 rows x 2 columns]

In [168]:
df.dtypes

Date          str
Time          str
Wind dir      str
Wind spd      str
Wind gust     str
Tmp           str
Dew pt        str
Feels like    str
rh            str
Fire          str
Rain          str
Rain 10'      str
Pres          str
dtype: object

In [169]:
df = df.rename(columns={
    "Date": "observation_date",
    "Time": "observation_time",
    "Wind dir": "wind_direction",
    "Wind spd": "wind_speed",
    "Wind gust": "wind_gust_speed",
    "Tmp": "temperature",
    "Dew pt": "dew_point",
    "Feels like": "feels_like_temperature",
    "rh": "relative_humidity",
    "Fire": "fire_index",
    "Rain": "rainfall",
    "Rain 10'": "rainfall_10min",
    "Pres": "air_pressure"
})

In [170]:
df.head()

,observation_date,observation_time,wind_direction,wind_speed,wind_gust_speed,temperature,dew_point,feels_like_temperature,relative_humidity,fire_index,rainfall,rainfall_10min,air_pressure
0,01/01/2013,Wed 00:00 EDT,WNW,9,9,19.6,0.1,19.6,27,12,0.0,0.0,1011.4
1,01/01/2013,Tue 23:30 EDT,WNW,-,13,20.7,0.7,20.7,26,13,0.0,0.0,1011.1
2,01/01/2013,Tue 23:00 EDT,W,9,11,22.8,0.9,22.8,23,15,0.0,0.0,1011.0
3,01/01/2013,Tue 22:30 EDT,WNW,11,13,22.6,-1.0,22.6,21,17,0.0,0.0,1011.0
4,01/01/2013,Tue 22:00 EDT,WNW,15,19,23.9,-2.2,23.9,18,21,0.0,0.0,1011.1

In [171]:
df["wind_direction"].value_counts(dropna=False)

wind_direction
-      1963
N      1940
NNW    1937
NW     1891
E      1672
WNW    1639
S      1319
ESE    1307
SE     1237
SSE    1136
W      1009
ENE     791
NNE     636
NE      564
SSW     356
WSW     285
SW      236
Name: count, dtype: int64

In [172]:
df["wind_direction"]= df["wind_direction"].replace("-", np.nan)

In [173]:
df["wind_direction"].value_counts(dropna=False)

wind_direction
NaN    1963
N      1940
NNW    1937
NW     1891
E      1672
WNW    1639
S      1319
ESE    1307
SE     1237
SSE    1136
W      1009
ENE     791
NNE     636
NE      564
SSW     356
WSW     285
SW      236
Name: count, dtype: int64

In [174]:
df["observation_time"].str.split(" ", expand=True)

         0      1    2
0      Wed  00:00  EDT
1      Tue  23:30  EDT
2      Tue  23:00  EDT
3      Tue  22:30  EDT
4      Tue  22:00  EDT
...    ...    ...  ...
19913  Tue  01:37  EDT
19914  Tue  01:30  EDT
19915  Tue  01:00  EDT
19916  Tue  00:30  EDT
19917  Tue  00:00  EDT

[19918 rows x 3 columns]

In [175]:
df["observation_time"] = df["observation_time"].str.split(" ").str[1]

In [176]:
df["observation_time"].value_counts(dropna=False)

observation_time
00:00    726
18:00    365
15:00    365
13:00    365
11:00    365
        ...
06:25      1
20:27      1
18:03      1
15:21      1
06:58      1
Name: count, Length: 1087, dtype: int64

In [177]:
df["wind_speed"].value_counts(dropna=False)

wind_speed
9     2280
7     2118
0     1939
6     1536
13    1408
11    1364
17     985
15     906
20     857
19     768
4      711
2      708
24     697
28     653
22     555
26     493
30     444
31     411
33     255
35     237
37     163
39     141
41      98
43      66
44      34
46      26
-       24
48      19
50       8
52       5
57       5
65       2
59       1
69       1
Name: count, dtype: int64

In [178]:
df["wind_speed"] = df["wind_speed"].replace("-", np.nan)

In [179]:
df["wind_speed"] = pd.to_numeric(df["wind_speed"])

In [180]:
df.dtypes

observation_date              str
observation_time           object
wind_direction                str
wind_speed                float64
wind_gust_speed               str
temperature                   str
dew_point                     str
feels_like_temperature        str
relative_humidity             str
fire_index                    str
rainfall                      str
rainfall_10min                str
air_pressure                  str
dtype: object

In [181]:
df["observation_date"] = pd.to_datetime(df["observation_date"], dayfirst=True)

In [182]:
df.dtypes

observation_date          datetime64[us]
observation_time                  object
wind_direction                       str
wind_speed                       float64
wind_gust_speed                      str
temperature                          str
dew_point                            str
feels_like_temperature               str
relative_humidity                    str
fire_index                           str
rainfall                             str
rainfall_10min                       str
air_pressure                         str
dtype: object

In [183]:
df.dtypes

observation_date          datetime64[us]
observation_time                  object
wind_direction                       str
wind_speed                       float64
wind_gust_speed                      str
temperature                          str
dew_point                            str
feels_like_temperature               str
relative_humidity                    str
fire_index                           str
rainfall                             str
rainfall_10min                       str
air_pressure                         str
dtype: object

In [184]:
df["wind_gust_speed"] = df["wind_gust_speed"].replace("-", np.nan)

In [185]:
df["wind_gust_speed"] = pd.to_numeric(df["wind_gust_speed"])

In [186]:
df.dtypes

observation_date          datetime64[us]
observation_time                  object
wind_direction                       str
wind_speed                       float64
wind_gust_speed                  float64
temperature                          str
dew_point                            str
feels_like_temperature               str
relative_humidity                    str
fire_index                           str
rainfall                             str
rainfall_10min                       str
air_pressure                         str
dtype: object

In [187]:
df["temperature"] = df["temperature"].replace("-", None)

In [188]:
df["temperature"] = pd.to_numeric(df["temperature"])

In [189]:
df["dew_point"] = df["dew_point"].replace("-", None)
df["dew_point"] = pd.to_numeric(df["dew_point"])

df["feels_like_temperature"] = df["feels_like_temperature"].replace("-", None)
df["feels_like_temperature"] = pd.to_numeric(df["feels_like_temperature"])

df["dew_point"] = df["dew_point"].replace("-", None)
df["dew_point"] = pd.to_numeric(df["dew_point"])

df["feels_like_temperature"] = df["feels_like_temperature"].replace("-", None)
df["feels_like_temperature"] = pd.to_numeric(df["feels_like_temperature"])

df[["relative_humidity", "rainfall", "rainfall_10min", "air_pressure"]] = \
    df[["relative_humidity", "rainfall", "rainfall_10min", "air_pressure"]].replace("-", None)
df["fire_index"] = df["fire_index"].replace("-", None)

df["relative_humidity"] = pd.to_numeric(df["relative_humidity"])
df["rainfall"] = pd.to_numeric(df["rainfall"])
df["rainfall_10min"] = pd.to_numeric(df["rainfall_10min"])
df["air_pressure"] = pd.to_numeric(df["air_pressure"])

In [190]:
df.dtypes

observation_date          datetime64[us]
observation_time                  object
wind_direction                       str
wind_speed                       float64
wind_gust_speed                  float64
temperature                      float64
dew_point                        float64
feels_like_temperature           float64
relative_humidity                float64
fire_index                           str
rainfall                         float64
rainfall_10min                   float64
air_pressure                     float64
dtype: object

In [191]:
df.head()

,observation_date,observation_time,wind_direction,wind_speed,wind_gust_speed,temperature,dew_point,feels_like_temperature,relative_humidity,fire_index,rainfall,rainfall_10min,air_pressure
0,2013-01-01,00:00,WNW,9.0,9.0,19.6,0.1,19.6,27.0,12,0.0,0.0,1011.4
1,2013-01-01,23:30,WNW,NaN,13.0,20.7,0.7,20.7,26.0,13,0.0,0.0,1011.1
2,2013-01-01,23:00,W,9.0,11.0,22.8,0.9,22.8,23.0,15,0.0,0.0,1011.0
3,2013-01-01,22:30,WNW,11.0,13.0,22.6,-1.0,22.6,21.0,17,0.0,0.0,1011.0
4,2013-01-01,22:00,WNW,15.0,19.0,23.9,-2.2,23.9,18.0,21,0.0,0.0,1011.1

In [192]:
df = df.sort_values(by=["observation_date", "observation_time"]).reset_index(drop=True)

In [193]:
df.head()

,observation_date,observation_time,wind_direction,wind_speed,wind_gust_speed,temperature,dew_point,feels_like_temperature,relative_humidity,fire_index,rainfall,rainfall_10min,air_pressure
0,2013-01-01,00:00,WNW,9.0,9.0,19.6,0.1,19.6,27.0,12,0.0,0.0,1011.4
1,2013-01-01,00:00,ENE,2.0,6.0,15.9,3.7,15.9,44.0,5,0.0,0.0,1014.1
2,2013-01-01,00:30,NaN,0.0,0.0,14.5,4.7,14.5,52.0,3,0.0,0.0,1014.0
3,2013-01-01,01:00,NaN,0.0,0.0,12.8,4.6,12.8,57.0,3,0.0,0.0,1013.5
4,2013-01-01,01:30,SSW,6.0,9.0,13.3,5.9,13.3,61.0,3,0.0,0.0,1013.4

In [194]:
import psycopg2

In [195]:
conn = psycopg2.connect(
    host = "localhost",
    port = 5432,
    database = "weather2",
    user = "postgres",
    password = "994583"
)

In [196]:
cursor = conn.cursor()

In [197]:
cursor.execute("SELECT * FROM weather2;")

In [198]:
print(cursor)

<cursor object at 0x000001C17F60E0A0; closed: 0>

In [199]:
row = cursor.fetchall()
print(row)

[]

In [200]:
df.dtypes

observation_date          datetime64[us]
observation_time                  object
wind_direction                       str
wind_speed                       float64
wind_gust_speed                  float64
temperature                      float64
dew_point                        float64
feels_like_temperature           float64
relative_humidity                float64
fire_index                           str
rainfall                         float64
rainfall_10min                   float64
air_pressure                     float64
dtype: object

In [201]:
df_load = df.astype(object).where(pd.notna(df), None)

In [202]:
sql = """ INSERT INTO weather2 (
    observation_date,
    observation_time,
    wind_direction,
    wind_speed_kmh,
    wind_gust_speed_kmh,
    temperature_c,
    dew_point_c,
    feels_like_temperature_c,
    relative_humidity_percent,
    fire_index,
    rainfall_mm,
    rainfall_10min_mm,
    air_pressure_hpa
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

In [203]:
for _, row in df_load.iterrows():
    cursor.execute(sql, (
        row["observation_date"],
        row["observation_time"],
        row["wind_direction"],
        row["wind_speed"],
        row["wind_gust_speed"],
        row["temperature"],
        row["dew_point"],
        row["feels_like_temperature"],
        row["relative_humidity"],
        row["fire_index"],
        row["rainfall"],
        row["rainfall_10min"],
        row["air_pressure"]
    ))

In [204]:
df[df["fire_index"] == "-"][["fire_index"]]

Empty DataFrame
Columns: [fire_index]
Index: []

In [206]:
conn.commit()