In [276]:
import pandas as pd

In [277]:
import os
os.getcwd()

'c:\\Users\\SREESHANTH_K\\Desktop\\etl'

In [ ]:
df = pd.read_csv("datasets\Canberra_sky.csv")

In [279]:
df.head()

  Date\tTime\tVis\tCloud\tCurrent weather\tPast weather\t?
0              01/01/2013\tWed 00:00 EDT\t-\t-\t-\t-
1              01/01/2013\tTue 23:00 EDT\t-\t-\t-\t-
2              01/01/2013\tTue 21:00 EDT\t-\t-\t-\t-
3              01/01/2013\tTue 20:00 EDT\t-\t-\t-\t-
4              01/01/2013\tTue 18:00 EDT\t-\t-\t-\t-

In [280]:
df.shape

(6171, 1)

In [281]:
with open("Canberra_sky.csv", "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

Date	Time	Vis	Cloud	Current weather	Past weather	?

01/01/2013	Wed 00:00 EDT	-	-	-	-

01/01/2013	Tue 23:00 EDT	-	-	-	-

01/01/2013	Tue 21:00 EDT	-	-	-	-

01/01/2013	Tue 20:00 EDT	-	-	-	-

In [282]:
df = pd.read_csv("Canberra_sky.csv", sep='\t')

In [283]:
df.head()

         Date           Time Vis Cloud Current weather Past weather    ?
0  01/01/2013  Wed 00:00 EDT   -     -               -            -  NaN
1  01/01/2013  Tue 23:00 EDT   -     -               -            -  NaN
2  01/01/2013  Tue 21:00 EDT   -     -               -            -  NaN
3  01/01/2013  Tue 20:00 EDT   -     -               -            -  NaN
4  01/01/2013  Tue 18:00 EDT   -     -               -            -  NaN

In [284]:
df.shape

(6171, 7)

In [285]:
df.info

<bound method DataFrame.info of             Date           Time Vis Cloud Current weather Past weather    ?
0     01/01/2013  Wed 00:00 EDT   -     -               -            -  NaN
1     01/01/2013  Tue 23:00 EDT   -     -               -            -  NaN
2     01/01/2013  Tue 21:00 EDT   -     -               -            -  NaN
3     01/01/2013  Tue 20:00 EDT   -     -               -            -  NaN
4     01/01/2013  Tue 18:00 EDT   -     -               -            -  NaN
...          ...            ...  ..   ...             ...          ...  ...
6166  31/12/2013  Tue 06:00 EDT   -   5/8               -            -  NaN
6167  31/12/2013  Tue 05:00 EDT   -     -               -            -  NaN
6168  31/12/2013  Tue 03:00 EDT   -   5/8               -            -  NaN
6169  31/12/2013  Tue 02:00 EDT   -     -               -            -  NaN
6170  31/12/2013  Tue 00:00 EDT   -     -               -            -  NaN

[6171 rows x 7 columns]>

In [286]:
df.columns

Index(['Date', 'Time', 'Vis', 'Cloud', 'Current weather', 'Past weather', '?'], dtype='str')

In [287]:
df.isnull().sum()

Date                  0
Time                  0
Vis                   0
Cloud                 0
Current weather      40
Past weather        192
?                  6170
dtype: int64

In [288]:
df['Cloud'].value_counts()

Cloud
-           4743
8/8          657
1/8          215
7/8          162
2/8          109
6/8           75
5/8           74
3/8           64
4/8           60
clear         11
obscured       1
Name: count, dtype: int64

In [289]:
df["?"].value_counts(dropna=False)

?
NaN    6170
-         1
Name: count, dtype: int64

In [290]:
df.duplicated().sum()

np.int64(0)

In [291]:
df.isnull().sum()

Date                  0
Time                  0
Vis                   0
Cloud                 0
Current weather      40
Past weather        192
?                  6170
dtype: int64

In [292]:
df["Current weather"].value_counts(dropna=False)

Current weather
-      6131
NaN      40
Name: count, dtype: int64

In [293]:
df["Past weather"].value_counts(dropna=False)

Past weather
-      5979
NaN     192
Name: count, dtype: int64

In [294]:
df["Vis"].value_counts(dropna=False)

Vis
-        5999
5000       18
400        12
300        11
25000      10
6000       10
9000       10
8000       10
100        10
200         8
500         7
15000       6
20000       6
7000        6
10000       5
30000       4
1000        3
2000        3
1400        3
3200        3
4900        3
35000       2
0           2
4100        2
700         2
600         2
3900        2
40000       1
3300        1
3500        1
2500        1
1100        1
2400        1
4000        1
3600        1
4300        1
1600        1
3000        1
4500        1
Name: count, dtype: int64

In [295]:
df.dtypes

Date               str
Time               str
Vis                str
Cloud              str
Current weather    str
Past weather       str
?                  str
dtype: object

In [296]:
df["Vis"].value_counts().head(20)

Vis
-        5999
5000       18
400        12
300        11
25000      10
6000       10
9000       10
8000       10
100        10
200         8
500         7
15000       6
20000       6
7000        6
10000       5
30000       4
1000        3
2000        3
1400        3
3200        3
Name: count, dtype: int64

In [297]:
df["Cloud"].value_counts().head(20)

Cloud
-           4743
8/8          657
1/8          215
7/8          162
2/8          109
6/8           75
5/8           74
3/8           64
4/8           60
clear         11
obscured       1
Name: count, dtype: int64

In [298]:
df = df.drop(columns=['Current weather', 'Past weather', '?'])

In [299]:
df.head

<bound method NDFrame.head of             Date           Time Vis Cloud
0     01/01/2013  Wed 00:00 EDT   -     -
1     01/01/2013  Tue 23:00 EDT   -     -
2     01/01/2013  Tue 21:00 EDT   -     -
3     01/01/2013  Tue 20:00 EDT   -     -
4     01/01/2013  Tue 18:00 EDT   -     -
...          ...            ...  ..   ...
6166  31/12/2013  Tue 06:00 EDT   -   5/8
6167  31/12/2013  Tue 05:00 EDT   -     -
6168  31/12/2013  Tue 03:00 EDT   -   5/8
6169  31/12/2013  Tue 02:00 EDT   -     -
6170  31/12/2013  Tue 00:00 EDT   -     -

[6171 rows x 4 columns]>

In [300]:
import numpy as np
df.replace('-', np.nan)

            Date           Time  Vis Cloud
0     01/01/2013  Wed 00:00 EDT  NaN   NaN
1     01/01/2013  Tue 23:00 EDT  NaN   NaN
2     01/01/2013  Tue 21:00 EDT  NaN   NaN
3     01/01/2013  Tue 20:00 EDT  NaN   NaN
4     01/01/2013  Tue 18:00 EDT  NaN   NaN
...          ...            ...  ...   ...
6166  31/12/2013  Tue 06:00 EDT  NaN   5/8
6167  31/12/2013  Tue 05:00 EDT  NaN   NaN
6168  31/12/2013  Tue 03:00 EDT  NaN   5/8
6169  31/12/2013  Tue 02:00 EDT  NaN   NaN
6170  31/12/2013  Tue 00:00 EDT  NaN   NaN

[6171 rows x 4 columns]

In [301]:
df.isnull().sum()

Date     0
Time     0
Vis      0
Cloud    0
dtype: int64

In [302]:
df.duplicated().sum()

np.int64(0)

In [303]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

In [304]:
df.head

<bound method NDFrame.head of            Date           Time Vis Cloud
0    2013-01-01  Wed 00:00 EDT   -     -
1    2013-01-01  Tue 23:00 EDT   -     -
2    2013-01-01  Tue 21:00 EDT   -     -
3    2013-01-01  Tue 20:00 EDT   -     -
4    2013-01-01  Tue 18:00 EDT   -     -
...         ...            ...  ..   ...
6166 2013-12-31  Tue 06:00 EDT   -   5/8
6167 2013-12-31  Tue 05:00 EDT   -     -
6168 2013-12-31  Tue 03:00 EDT   -   5/8
6169 2013-12-31  Tue 02:00 EDT   -     -
6170 2013-12-31  Tue 00:00 EDT   -     -

[6171 rows x 4 columns]>

In [305]:
df["Time"].str.extract(r'(\d{2}:\d{2})').head()

       0
0  00:00
1  23:00
2  21:00
3  20:00
4  18:00

In [306]:
df["Time"] = df["Time"].str.extract(r'(\d{2}:\d{2})')

In [307]:
df[["Date", "Time"]].head(10)

        Date   Time
0 2013-01-01  00:00
1 2013-01-01  23:00
2 2013-01-01  21:00
3 2013-01-01  20:00
4 2013-01-01  18:00
5 2013-01-01  17:00
6 2013-01-01  15:00
7 2013-01-01  14:00
8 2013-01-01  12:00
9 2013-01-01  11:00

In [308]:
df['Vis'].head(20)

0     -
1     -
2     -
3     -
4     -
5     -
6     -
7     -
8     -
9     -
10    -
11    -
12    -
13    -
14    -
15    -
16    -
17    -
18    -
19    -
Name: Vis, dtype: str

In [309]:
df["Vis"].value_counts(dropna=False).head(20)

Vis
-        5999
5000       18
400        12
300        11
25000      10
6000       10
9000       10
8000       10
100        10
200         8
500         7
15000       6
20000       6
7000        6
10000       5
30000       4
1000        3
2000        3
1400        3
3200        3
Name: count, dtype: int64

In [310]:
df["Vis"] = df["Vis"].replace("-", np.nan)

In [311]:
df['Vis'] = pd.to_numeric(df["Vis"])

In [312]:
df.dtypes

Date     datetime64[us]
Time                str
Vis             float64
Cloud               str
dtype: object

In [313]:
df["Cloud"].value_counts(dropna=False)

Cloud
-           4743
8/8          657
1/8          215
7/8          162
2/8          109
6/8           75
5/8           74
3/8           64
4/8           60
clear         11
obscured       1
Name: count, dtype: int64

In [314]:
df["Cloud"] = df["Cloud"].replace("-", np.nan)

In [315]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6171 entries, 0 to 6170
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6171 non-null   datetime64[us]
 1   Time    6171 non-null   str
 2   Vis     172 non-null    float64
 3   Cloud   1428 non-null   str
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 193.0 KB

In [316]:
import psycopg2

In [317]:
conn = psycopg2.connect(
    host = "localhost",
    port = 5432,
    database = "weather",
    user = "postgres",
    password = "994583"
)

In [318]:
cursor = conn.cursor()

In [319]:
cursor.execute("SELECT * FROM weather;")

In [320]:
print(conn)

<connection object at 0x00000212C0107AB0; dsn: 'user=postgres password=xxx dbname=weather host=localhost port=5432', closed: 0>

In [321]:
row = cursor.fetchall()
print(row)

[(datetime.date(2013, 1, 1), datetime.time(0, 0), None, 'NaN'), (datetime.date(2013, 1, 5), datetime.time(9, 0), 25000, 'clear'), (datetime.date(2013, 1, 1), datetime.time(0, 0), None, 'NaN')]

In [322]:
type(df.iloc[0]["Date"])

pandas.Timestamp

In [323]:
type(df.iloc[0]["Time"])

str

In [324]:
type(df.iloc[0]["Vis"])

numpy.float64

In [325]:
sql = """
INSERT INTO weather (date, time, visibility, cloud)
VALUES (%s, %s, %s, %s);
"""

In [326]:
row = df.iloc[0]
print(row)

Date     2013-01-01 00:00:00
Time                   00:00
Vis                      NaN
Cloud                    NaN
Name: 0, dtype: object

In [327]:
conn.commit()

In [328]:
df = df.where(pd.notna(df), None)

In [329]:
df.iloc[0]

Date     2013-01-01 00:00:00
Time                   00:00
Vis                      NaN
Cloud                    NaN
Name: 0, dtype: object

In [330]:
df[df["Vis"].notna()].iloc[0]

Date     2013-01-05 00:00:00
Time                   09:00
Vis                  25000.0
Cloud                  clear
Name: 78, dtype: object

In [331]:
sql = """
INSERT INTO weather (date, time, visibility, cloud)
VALUES (%s, %s, %s, %s);
"""

In [332]:
test_row = df[df["Vis"].notna()].iloc[0]

In [333]:
test_row

Date     2013-01-05 00:00:00
Time                   09:00
Vis                  25000.0
Cloud                  clear
Name: 78, dtype: object

In [334]:
vis_value = float(test_row["Vis"])

In [335]:
print(vis_value)
print(type(vis_value))

25000.0
<class 'float'>

In [336]:
cursor.execute("SELECT * FROM weather;")
print(cursor.fetchall())

[(datetime.date(2013, 1, 1), datetime.time(0, 0), None, 'NaN'), (datetime.date(2013, 1, 5), datetime.time(9, 0), 25000, 'clear'), (datetime.date(2013, 1, 1), datetime.time(0, 0), None, 'NaN')]

In [340]:
conn.rollback()

In [341]:
conn.rollback()

In [342]:
for index, row in df.iterrows():

    vis = row["Vis"]
    cloud = row["Cloud"]

    if pd.isna(vis):
        vis = None

    if pd.isna(cloud):
        cloud = None

    cursor.execute(sql, (
        row["Date"],
        row["Time"],
        vis,
        cloud
    ))

conn.commit()